//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientConsoleAppStudy.WcfserviceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Info", Namespace="http://schemas.datacontract.org/2004/07/DatabaseFirstStudy")]
    [System.SerializableAttribute()]
    public partial class Info : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfserviceReference.IDBoperationService")]
    public interface IDBoperationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBoperationService/Create", ReplyAction="http://tempuri.org/IDBoperationService/CreateResponse")]
        bool Create(ClientConsoleAppStudy.WcfserviceReference.Info info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBoperationService/Retrieve", ReplyAction="http://tempuri.org/IDBoperationService/RetrieveResponse")]
        ClientConsoleAppStudy.WcfserviceReference.Info[] Retrieve();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBoperationService/Update", ReplyAction="http://tempuri.org/IDBoperationService/UpdateResponse")]
        bool Update(ClientConsoleAppStudy.WcfserviceReference.Info info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBoperationService/Delete", ReplyAction="http://tempuri.org/IDBoperationService/DeleteResponse")]
        bool Delete(ClientConsoleAppStudy.WcfserviceReference.Info info);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDBoperationServiceChannel : ClientConsoleAppStudy.WcfserviceReference.IDBoperationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DBoperationServiceClient : System.ServiceModel.ClientBase<ClientConsoleAppStudy.WcfserviceReference.IDBoperationService>, ClientConsoleAppStudy.WcfserviceReference.IDBoperationService {
        
        public DBoperationServiceClient() {
        }
        
        public DBoperationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DBoperationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBoperationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBoperationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Create(ClientConsoleAppStudy.WcfserviceReference.Info info) {
            return base.Channel.Create(info);
        }
        
        public ClientConsoleAppStudy.WcfserviceReference.Info[] Retrieve() {
            return base.Channel.Retrieve();
        }
        
        public bool Update(ClientConsoleAppStudy.WcfserviceReference.Info info) {
            return base.Channel.Update(info);
        }
        
        public bool Delete(ClientConsoleAppStudy.WcfserviceReference.Info info) {
            return base.Channel.Delete(info);
        }
    }
}
